includes:
  - base.yaml
model:
  model_name: EERMGCN
ood:
  ood_alg: EERM
  ood_param: 1.
  extra_param:
    - 5   # K: Number of context generator
    - 1   # T
    - 1   # Number of sample
    - 5e-4    # Learning rate for REINFORCE
train:
  max_epoch: 100
  lr: 1e-3
  mile_stones: [150]

