exp_round:
  - 1
  - 2
  - 3
log_file:
  - lb_sweeping
lr:
  - 1e-3
weight_decay:
  - 0.
num_workers:
  - 8
clean_save:           # Comment it to make it false. Att: Setting it to false won't take effect.
  - true