includes:
  - base.yaml
model:
  model_name: CIGAvGIN
ood:
  ood_alg: CIGA
  ood_param: 0.8
  extra_param:
    - 1
    - 0
train:
  max_epoch: 200
  train_bs: 128
  lr: 0.001
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 8
clean_save: true
