includes:
  - base.yaml
model:
  model_name: GSATvGIN
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - true
    - 10
    - 0.7
train:
  max_epoch: 200
  train_bs: 64
  val_bs: 128
  test_bs: 128
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
