includes:
  - base.yaml
model:
  model_name: GSATvGIN
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - true
    - 10
    - 0.5
train:
  max_epoch: 200
  lr: 0.001
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
