includes:
  - base.yaml
model:
  model_name: DIRGIN
ood:
  ood_alg: DIR
  ood_param: 0.7
  extra_param:
    - 0.01
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
