includes:
  - base.yaml
model:
  model_name: GIN
ood:
  ood_alg: VREx
  ood_param: 100.0
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
