includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
  ood_param: 0.25
  extra_param:
    - 0.1
train:
  max_epoch: 200
  lr: 0.001
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
