includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
  ood_param: 0.8
  extra_param:
    - 1
train:
  max_epoch: 200
  train_bs: 32
  lr: 0.001
  weight_decay: 0.0
log_file: lb_sweeping
num_workers: 0
